---
title: "analysis_virality"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash, include=FALSE}
list.packages <- c('tidyverse', 
                   'readxl',
                   'plm', 
                   'stats', 
                   'lmtest', 
                   'multiwayvcov', 
                   'car',
                   'sandwich')

lapply(list.packages,
       require,
       character.only = TRUE)
```

```{r}
setwd('~/misinformation_socialmedia/data/')
load('5-analysis/1-input_data/data_reg.Rda', verbose = TRUE)
```


## R Markdown

Difference-in-differences analysis 

# 1. Cases where news/posts were verified as false/true

## Sepecification

```{r pressure, echo=FALSE}
dep.var <- c('change_likes', 
             'change_comments', 
             'change_shares', 
             'change_reactions')
factcheck.var <- 'factcheck.var'
group.var <- 'label_desinformacion'
interaction <- 'factcheck.var*label_desinformacion'

```

```{r}
## Run regression

fit.main <- coef.main <- se.cse.disaggregated.1 <- vector("list", length(dep.var))

for (i in 1:length(dep.var)){
  formula1 <- as.formula(paste0(dep.var[[i]], 
                              '~', 
                              factcheck.var, 
                              '+', 
                              group.var, 
                              '+', 
                              interaction))
  
  fit.main[[i]] <- lm(formula1, 
   data = subset_social2)
}

```


```{r}
stargazer::stargazer(fit.main[[1]],
                     fit.main[[2]], 
                     fit.main[[3]], 
                     fit.main[[4]],
                     type = 'text', 
                     covariate.labels = c('fact check', 
                                          'label true', 
                                          'factcheck:labeltrue'))
```

# 1. Cases where news/posts were verified as false/true

## Sepecification


```{r pressure, echo=FALSE}
dep.var <- c('change_likes', 
             'change_comments', 
             'change_shares', 
             'change_reactions')
factcheck.var <- 'factcheck.var'
group.var <- 'poynter_facebook'
interaction <- 'factcheck.var*poynter_facebook'
```

```{r}
## Run regression

fit.main <- coef.main <- se.cse.disaggregated.1 <- vector("list", length(dep.var))

for (i in 1:length(dep.var)){
  formula1 <- as.formula(paste0(dep.var[[i]], 
                              '~', 
                              factcheck.var, 
                              '+', 
                              group.var, 
                              '+', 
                              interaction))
  
  fit.main[[i]] <- lm(formula1, 
   data = social)
}

```


```{r}
stargazer::stargazer(fit.main[[1]],
                     fit.main[[2]], 
                     fit.main[[3]], 
                     fit.main[[4]],
                     type = 'text', 
                     covariate.labels = c('fact check', 
                                          'poynter', 
                                          'factcheck*poynter'))
```



